### ISSUE TITLE
Installer uses bad command when modifying

### ISSUE THREAD

**Issue by mattleibow** [devlooped/dotnet-vs#111] opened 2021-09-15 16:11 UTC
## Describe the Bug

I noticed a workload was not installing:

```
dotnet vs modify preview Enterprise --add Microsoft.VisualStudio.Component.Windows10SDK.18362 --quiet
```

Resulted in this bad command:

```
C:\Users\VssAdministrator\AppData\Local\Temp\7b17dee0-c4ee-4376-be45-e361dcb0bdb8\vs_enterprise.exe modify --wait --force --passive --add --installPath "C:\Program Files\Microsoft Visual Studio\2022\Preview" Microsoft.VisualStudio.Component.Windows10SDK.18362 --quiet
```

More specifically:

```
--add --installPath "<path>" <id>
```

As a result, that workload was not installed.

## Version Info

1.1.0

**Comment by mattleibow** [comment] 2021-09-15 16:42
Or maybe I am just having an issue installing that one SDK?

**Comment by kzu** [comment] 2021-11-05 18:34
Closing tentatively since it seems it's external. Plz reopen @mattleibow if this is still an issue and you cannot reproduce by invoking the vs installer itself.

Thanks!

**Closed by kzu** 2021-11-05 18:34 UTC
Labels: bug
